<script lang="ts">
  import type { GithubStats } from '$lib/server/github';
  import { theme } from '$lib/theme.svelte';

  let { stats } = $props<{ stats: GithubStats }>();
</script>

<div class="space-y-8">
  <h2 class="text-4xl font-black italic {theme.current.textPrimary}">Keep Coding!</h2>
  <div class="rounded-2xl border {theme.current.border} {theme.current.cardBg} p-6 backdrop-blur-md">
    <p class="text-lg leading-relaxed {theme.current.textSecondary}">
      "Another year of commits, another year of growth. The world runs on code, and you are building
      it."
    </p>
  </div>
  <div class="pt-8 text-sm opacity-50 {theme.current.textMuted}">Generated by Annual Git Review</div>
</div>
