<script lang="ts">
  import type { GithubStats } from '$lib/server/github';

  let { stats } = $props<{ stats: GithubStats }>();
</script>

<div class="space-y-8">
  <h2 class="text-4xl font-black italic">Keep Coding!</h2>
  <div class="rounded-2xl border border-white/20 bg-white/10 p-6 backdrop-blur-md">
    <p class="text-lg leading-relaxed">
      "Another year of commits, another year of growth. The world runs on code, and you are building
      it."
    </p>
  </div>
  <div class="pt-8 text-sm opacity-50">Generated by Annual Git Review</div>
</div>
