<script lang="ts">
  import { X } from 'lucide-svelte';
  import { fade, scale } from 'svelte/transition';
  import { settings } from '$lib/settings.svelte';
  import * as m from '$lib/paraglide/messages';

  let { onClose } = $props<{ onClose: () => void }>();
</script>

<div
  class="fixed inset-0 z-60 flex items-center justify-center bg-black/60 backdrop-blur-sm"
  transition:fade
>
  <div
    class="w-full max-w-sm rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"
    in:scale={{ start: 0.95 }}
  >
    <div class="mb-6 flex items-center justify-between">
      <h2 class="text-xl font-bold text-white">{m.settings_title()}</h2>
      <button onclick={onClose} class="text-white/60 hover:text-white">
        <X size={24} />
      </button>
    </div>

    <div class="space-y-6">
      <!-- Language Count Setting -->
      <div class="space-y-2">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium tracking-wider text-white/50 uppercase">
            {m.settings_language_count()}
          </h3>
          <span class="text-sm font-bold text-white">{settings.languageCount}</span>
        </div>
        <input
          type="range"
          min="1"
          max="10"
          step="1"
          bind:value={settings.languageCount}
          class="h-2 w-full cursor-pointer appearance-none rounded-lg bg-white/10 accent-emerald-500"
        />
        <p class="text-xs text-white/40">
          {m.settings_language_count_desc()}
        </p>
      </div>

      <!-- Repo Count Setting -->
      <div class="space-y-2">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium tracking-wider text-white/50 uppercase">
            {m.settings_repo_count()}
          </h3>
          <span class="text-sm font-bold text-white">{settings.repoCount}</span>
        </div>
        <input
          type="range"
          min="1"
          max="6"
          step="1"
          bind:value={settings.repoCount}
          class="h-2 w-full cursor-pointer appearance-none rounded-lg bg-white/10 accent-emerald-500"
        />
        <p class="text-xs text-white/40">
          {m.settings_repo_count_desc()}
        </p>
      </div>

      <!-- OSS Count Setting -->
      <div class="space-y-2">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium tracking-wider text-white/50 uppercase">
            {m.settings_oss_count()}
          </h3>
          <span class="text-sm font-bold text-white">{settings.ossCount}</span>
        </div>
        <input
          type="range"
          min="1"
          max="6"
          step="1"
          bind:value={settings.ossCount}
          class="h-2 w-full cursor-pointer appearance-none rounded-lg bg-white/10 accent-emerald-500"
        />
        <p class="text-xs text-white/40">
          {m.settings_oss_count_desc()}
        </p>
      </div>

      <!-- Show Green Wall Setting -->
      <div class="space-y-2">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium tracking-wider text-white/50 uppercase">
            {m.settings_show_green_wall()}
          </h3>
          <label class="relative inline-flex cursor-pointer items-center">
            <input type="checkbox" bind:checked={settings.showGreenWall} class="peer sr-only" />
            <div
              class="h-6 w-11 rounded-full bg-white/10 peer-checked:bg-emerald-500 peer-focus:outline-none after:absolute after:top-[2px] after:left-[2px] after:h-5 after:w-5 after:rounded-full after:bg-white after:transition-all after:content-[''] peer-checked:after:translate-x-full"
            ></div>
          </label>
        </div>
        <p class="text-xs text-white/40">
          {m.settings_show_green_wall_desc()}
        </p>
      </div>

      <!-- Show Footer Setting -->
      <div class="space-y-2">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium tracking-wider text-white/50 uppercase">Show Footer</h3>
          <label class="relative inline-flex cursor-pointer items-center">
            <input type="checkbox" bind:checked={settings.showFooter} class="peer sr-only" />
            <div
              class="h-6 w-11 rounded-full bg-white/10 peer-checked:bg-emerald-500 peer-focus:outline-none after:absolute after:top-[2px] after:left-[2px] after:h-5 after:w-5 after:rounded-full after:bg-white after:transition-all after:content-[''] peer-checked:after:translate-x-full"
            ></div>
          </label>
        </div>
        <p class="text-xs text-white/40">Display "Generated by annual-git-review" on slides.</p>
      </div>

      <!-- Show Snow Setting -->
      <div class="space-y-2">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-medium tracking-wider text-white/50 uppercase">Show Snow</h3>
          <label class="relative inline-flex cursor-pointer items-center">
            <input type="checkbox" bind:checked={settings.showSnow} class="peer sr-only" />
            <div
              class="h-6 w-11 rounded-full bg-white/10 peer-checked:bg-emerald-500 peer-focus:outline-none after:absolute after:top-[2px] after:left-[2px] after:h-5 after:w-5 after:rounded-full after:bg-white after:transition-all after:content-[''] peer-checked:after:translate-x-full"
            ></div>
          </label>
        </div>
        <p class="text-xs text-white/40">Toggle snowfall on the final slide.</p>
      </div>

    </div>
  </div>
</div>
